# Setup
title: Kovar1523's Devlog
name: Kovar1523's Devlog
description: Sometimes, it's good to look up at the stars in the night sky.
url: https://kovar1523dev.kro.kr
baseurl: ""
enforce_ssl: kovar1523dev.kro.kr
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg
date_format: "%Y-%m-%d"
logo: /assets/img/siteicon.png

plugins:
  - not-pure-poole
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
  - vendor
  - vendor/bundle
  - node_modules
  - _site
  - .jekyll-cache
  - .sass-cache


# Optimize Jekyl SEO Tag
social:
  name: Kovar1523's Devlog
  links:
    - https://github.com/Kovar1523
google_site_verification: xxxxx
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-TJ3QN3S11L

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Kovar1523
  url: https://github.com/Kovar1523
  email: kovar1523@gmali.com

# Comments (giscus)
giscus:
  repo: Kovar1523/Kovar1523.github.io
  repo_id: R_kgDOQ99x-Q
  category: "Q&A"
  category_id: DIC_kwDOQ99x-c4C1PMK
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: dark_dimmed
  lang: ko
